### ISSUE TITLE
trouble getting setup to work

### ISSUE THREAD

**Issue by CeleritasCelery** [jfhbrook/Cackledaemon#6]
This is a carry over from reddit. I am seeing several errors when trying to run the setup; included below:

```shell
PS C:\windows\system32> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://raw.githubuserconten
t.com/jfhbrook/Cackledaemon/master/InstallWizard.ps1')
Welcome to the Cackledaemon install wizard!

This script will guide you through the process of installing/updating Cackledaemon and Emacs.

Cackledaemon is already installed, but there might be updates..! :)
This script can optionally update the Cackledaemon module for the current user.

Do you want to reinstall Cackledaemon?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "Y"): Y

Installing the Cackledaemon module...
All done!
Time to initialize C:\Users\tjhinckl\AppData\Roaming\Cackledaemon!
By default, Cackledaemon will create these shortcuts inside the 'GNU Emacs' folder in the user's Start Menu when installing Emacs:

- C:\Users\tjhinckl\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Gnu Emacs\EmacsClient.lnk -> emacsclientw.exe

You may edit this config at C:\Users\tjhinckl\AppData\Roaming\Cackledaemon\Shortcuts.csv and re-run the Emacs install step at any time to change these shortcuts.

Do you want to use these shortcuts?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "Y"): Y

Checking the state of Emacs...

Get-Command : The term 'emacs.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:131 char:17
+ $EmacsCommand = Get-Command 'emacs.exe'
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (emacs.exe:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

Emacs needs to be installed!
This script will install Emacs for all users. It requires, and will prompt for, Administrator privileges.

Do you want to install Emacs?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "Y"): Y
Installing Emacs...
Invoke-AsAdministrator : A positional parameter cannot be found that accepts argument
'Files\WindowsPowerShell\Modules\Cackledaemon\0.1.1\Cackledaemon.psd1'.
At C:\Program Files\WindowsPowerShell\Modules\Cackledaemon\0.1.1\Cackledaemon.psm1:842 char:5
+     Invoke-AsAdministrator "
+     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

There are two errors in the code above. One about emacs.exe not found and another is with Invoke-AsAdministrator.

**Comment by jfhbrook** [comment]
OK, I can take a look. I might have to clean up my system and run this from scratch to get a full repro, but I think I can make fixes for these particular issues without the repro and I can definitely clarify what's going on.

The first one about not finding emacs.exe is expected since you don't have it installed :) but seeing an error message printed to the screen is not. PowerShell has what are called non-terminating errors, which are basically super-warnings. By default it'll continue as though nothing happened. My intent was to use this with the error output suppressed and then check that the output was null, but it looks like that's not working the way I think it is. So I think seeing that message is OK, but I do want to clean that up I'll take a closer look later in the week.

The second one is because you have an old version of PSeudo installed. It should be using [v1.0](https://www.powershellgallery.com/packages/PSeudo/1.0). I'm not sure why it installed an old version, but I think I can convince the .psd to enforce a minimum version. I'll look into that as well, but in the meantime you can install the new version, I believe with `Install-Module -Force -MinimumVersion 1.0`.

**Comment by jfhbrook** [comment]
Actually - I think even if you upgrade there might still be a quoting issue. :/ I'll try to dig into this tomorrow or Friday. Thanks for reporting!

**Comment by jfhbrook** [comment]
Alright, I close #7 and #8, as well as #10, so most of these issues should go away! I'll see what I can do about the quoting issue, though I also have a space in my path and haven't had that issue :/ Will update if I find anything, but in the meantime feel free to try v0.1.2!

**Comment by jfhbrook** [comment]
I have a fix for #10 coming up as well - though if you uninstall Cackledaemon as administrator and re-install Cackledaemon as your regular user (not as Administrator) /and your username doesn't have spaces/ it should behave. :)

**Comment by jfhbrook** [comment]
OK, #9 is fixed. v0.1.3 should address all of these bugs. Feel free to give it a shot! For best results, upgrade PowerShellGet to at least version 2.2, uninstall Cackledaemon from the administrator account and re-run the script as your current user.

Let me know how it goes! I'll keep the issue open until you report success.

**Comment by CeleritasCelery** [comment]
I tried it again with reinstalling cackledaemon and emacs with the script from the readme. I get the following error

```shell
Cackledaemon can also set up the current user's  environment by configuring the user's $Path and $HOME and by creating shortcuts. This touches the user's registry but doesn't require Administrator privileges.

Do you want to set up the user environment?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "Y"): Y
Setting up the user's environment...
Import-Csv : Could not find file 'C:\Users\tjhinckl\AppData\Roaming\Cackledaemon\Shortcuts.csv'.
At C:\Users\tjhinckl\Documents\WindowsPowerShell\Modules\Cackledaemon\0.1.4\Cackledaemon.psm1:77 char:5
+     Import-Csv -Path (Join-Path $CackledaemonWD './Shortcuts.csv') |  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Import-Csv], FileNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.ImportCsvCommand
```

**Comment by jfhbrook** [comment]
oof, ok, I must not have tested it when a user decided to not have shortcuts. I can patch that later today.

I wanted to thank you for being game with this and struggling through all these QA issues. There are lot more of them than I expected coming out of the gate and I feel bad.

**Comment by CeleritasCelery** [comment]
> I wanted to thank you for being game with this and struggling through all these QA issues. There are lot more of them than I expected coming out of the gate and I feel bad.

Don't feel bad. Getting software working on someone else's machine is hard. I am just happy you are willing to work with me.

**Comment by jfhbrook** [comment]
Alright, I put a patch in that makes it so that if the Shortcuts.csv file is missing it will leave the shortcuts directory unmodified. Go ahead and give it a spin!

**Comment by CeleritasCelery** [comment]
got a new one!

```
Do you want to set up the user environment?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "Y"): Y
Setting up the user's environment...
Unable to save shortcut "C:\Users\tjhinckl\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Gnu
Emacs\Cackledaemon.lnk".
At C:\Users\tjhinckl\Documents\WindowsPowerShell\Modules\Cackledaemon\0.1.5\Cackledaemon.psm1:666 char:3
+   $Shortcut.Save()
+   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException

Have a nice day!
```

**Comment by jfhbrook** [comment]
Oh interesting - I bet what happened here was that my GNU Emacs folder existed already because I'd used `pm.exe` and that the code isn't currently creating it. Easy fix.

**Comment by jfhbrook** [comment]
Alright, that one should be good.

**Comment by CeleritasCelery** [comment]
hmm. I am still seeing the same error as before. It seems it because the path `C:\Users\tjhinckl\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Gnu 
Emacs` does not exist.

**Comment by jfhbrook** [comment]
Wondering if it's running against v0.1.5 still? That can happen if you run the installer in a terminal that's already had it imported. You can see the version imported with `Get-Module Cackledaemon` and you can drop it by running `Remove-Module Cackledaemon` and re-import with `Import-Module Cackledaemon`.

**Comment by jfhbrook** [comment]
If it turns out that that's what happened - that the installer ran in a context that already had an old version of CD installed - maybe I should make the script do the remove-module ahead of time? 🤔

**Comment by CeleritasCelery** [comment]
No I have version 0.1.6

```shell
PS C:\windows\system32> Get-Module Cackledaemon

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.1.6      Cackledaemon                        {Disable-CDLogRotateJob, Enable-CDLogRotateJob, Get-EmacsD...


PS C:\windows\system32> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/jfhbrook/Cackledaemon/master/InstallWizard.ps1')
Welcome to the Cackledaemon install wizard!

This script will guide you through the process of installing/updating Cackledaemon and Emacs.

Cackledaemon is already installed, but there might be updates..! :)
This script can optionally update the Cackledaemon module for the current user.

Do you want to reinstall Cackledaemon?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "Y"): Y

Installing the Cackledaemon module...
All done!
C:\Users\tjhinckl\AppData\Roaming\Cackledaemon already exists - nothing to do here!
Checking the state of Emacs...

Emacs needs to be installed!
This script will install Emacs for all users. It requires, and will prompt for, Administrator privileges.

Do you want to install Emacs?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "Y"): Y
Installing Emacs...

Cackledaemon can also set up the current user's  environment by configuring the user's $Path and $HOME and by creating shortcuts. This touches the user's registry but doesn't require Administrator privileges.

Do you want to set up the user environment?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "Y"): Y
Setting up the user's environment...
Unable to save shortcut "C:\Users\tjhinckl\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Gnu
Emacs\Cackledaemon.lnk".
At C:\Users\tjhinckl\Documents\WindowsPowerShell\Modules\Cackledaemon\0.1.6\Cackledaemon.psm1:666 char:3
+   $Shortcut.Save()
+   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException

Have a nice day!
```

**Comment by jfhbrook** [comment]
OK, weird. I thought the test had this covered but I must be missing something. It's getting late here, but I'll see if I can reproduce this in the morning.

**Comment by jfhbrook** [comment]
Oh, *I* know what this is >_< I have two places that creates shortcuts - this is the *other* shortcut. 🤦‍♂️ I fixed the shortcuts for EmacsClient but didn't fix the one for the autostart widget. So that's what's going on there. I'll fix in the morning.

**Comment by jfhbrook** [comment]
OK, second case is fixed.

**Comment by CeleritasCelery** [comment]
That worked!

**Comment by jfhbrook** [comment]
Nice!! Glad to hear it.

Let me know if you run into any other issues!
